### ISSUE TITLE
cannot click element with xpath 'contains'

### ISSUE THREAD

**Issue by IonutMoldovan** [NTTDATA-UK/cinnamon#47]
Issue xpath nr1. -  issue BUG in framework , 

 
org.openqa.selenium.NoSuchElementException: Cannot find element using locator mechanism: By.xpath: //button[contains(text(),'Skip Part Exchange')] and conditions: present
For documentation on this error, please visit: https://www.seleniumhq.org/exceptions/no_such_element.html
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'LAPTOPARBS700', ip: '10.0.75.1', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_201'
Driver info: driver.version: unknown
at io.magentys.cinnamon.webdriver.elements.WebElementWrapper.lambda$0(WebElementWrapper.java:36)
at java.util.Optional.orElseThrow(Optional.java:290)
at io.magentys.cinnamon.webdriver.elements.WebElementWrapper.getWrappedElement(WebElementWrapper.java:36)
at io.magentys.cinnamon.webdriver.elements.WebElementWrapper.getText(WebElementWrapper.java:93)
at io.magentys.cinnamon.webdriver.elements.PageElementFacade.getText(PageElementFacade.java:74)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at io.magentys.cinnamon.webdriver.support.pagefactory.PageElementInterceptor.intercept(PageElementInterceptor.java:28)
at io.magentys.cinnamon.webdriver.elements.PageElement$$EnhancerByCGLIB$$1c2d059.getText(<generated>)

at ?.I Get

**Comment by DavidJohnAnsell** [comment]
To use an xpath locator strategy within Cinnamon please try the following:
1 add the locator to your project locator file (e.g. landingpage_locator.yml) e.g.
  xpath:
   search-button: '//button[contains(text(),"Skip Part Exchange")]'

2. add FindByKey annotation to your page class. e.g.
    @FindByKey("search-button")
    public PageElement searchButton;

3. Implement in your stepDefinition
    page.searchButton.waitUntil(clickable).click();
